import type { Brand, WatchProduct } from "./types";

export const mockBrands: Brand[] = [
  {
    handle: "rolex",
    name: "Rolex",
    displayLines: ["ROLEX"],
    tier: "haute",
    enquiry_only: true,
    tagline: "The crown of Swiss watchmaking",
    heritage:
      "Founded in 1905, Rolex has defined the modern luxury sports watch.",
    collection_handle: "rolex",
    logo: "/brands/rolex.png",
  },
  {
    handle: "audemars-piguet",
    name: "Audemars Piguet",
    displayLines: ["AUDEMARS", "PIGUET"],
    tier: "haute",
    enquiry_only: true,
    tagline: "To break the rules, you must first master them",
    heritage:
      "Since 1875, Audemars Piguet has pushed the boundaries of haute horlogerie.",
    collection_handle: "audemars-piguet",
  },
  {
    handle: "patek-philippe",
    name: "Patek Philippe",
    displayLines: ["PATEK", "PHILIPPE"],
    tier: "haute",
    enquiry_only: true,
    tagline: "You never actually own a Patek Philippe",
    heritage:
      "The last family-owned independent watch manufacturer in Geneva.",
    collection_handle: "patek-philippe",
  },
  {
    handle: "hublot",
    name: "Hublot",
    displayLines: ["HUBLOT"],
    tier: "haute",
    enquiry_only: false,
    tagline: "The art of fusion",
    heritage:
      "Hublot pioneered the fusion of precious materials with innovative design.",
    collection_handle: "hublot",
  },
  {
    handle: "tissot",
    name: "Tissot",
    displayLines: ["TISSOT"],
    tier: "premium",
    enquiry_only: false,
    tagline: "Innovators by tradition since 1853",
    heritage: "Tissot brings Swiss precision to accessible luxury.",
    collection_handle: "tissot",
  },
];

export const mockProducts: WatchProduct[] = [
  {
    id: "1",
    title: "Tissot · PRX · Powermatic 80 · T137.407.11.041.00",
    handle: "tissot-prx-powermatic-80-blue",
    vendor: "Tissot",
    tags: ["new", "featured"],
    price: "695.00",
    metafields: {
      line: "prx",
      reference_number: "T137.407.11.041.00",
      gender: "unisex",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 40,
      case_material: ["steel"],
      dial_color: "Blue",
      crystal: "Sapphire",
      water_resistance: "100m",
      strap_type: "bracelet",
      power_reserve: "80 hours",
      tier: "premium",
      purchase_mode: "checkout",
    },
  },
  {
    id: "2",
    title: "Tissot · PRX · Powermatic 80 · T137.407.11.351.00",
    handle: "tissot-prx-powermatic-80-green",
    vendor: "Tissot",
    tags: ["new", "bestseller"],
    price: "695.00",
    metafields: {
      line: "prx",
      reference_number: "T137.407.11.351.00",
      gender: "unisex",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 40,
      case_material: ["steel"],
      dial_color: "Green",
      crystal: "Sapphire",
      water_resistance: "100m",
      strap_type: "bracelet",
      power_reserve: "80 hours",
      tier: "premium",
      purchase_mode: "checkout",
    },
  },
  {
    id: "3",
    title: "Rolex · Submariner · Date · 126610LN",
    handle: "rolex-submariner-date-126610ln",
    vendor: "Rolex",
    tags: ["featured", "enquiry-only"],
    price: "0.00",
    metafields: {
      line: "submariner",
      reference_number: "126610LN",
      gender: "men",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 41,
      case_material: ["steel"],
      dial_color: "Black",
      crystal: "Sapphire",
      water_resistance: "300m",
      strap_type: "bracelet",
      power_reserve: "70 hours",
      tier: "luxury",
      purchase_mode: "enquiry",
    },
  },
  {
    id: "4",
    title: "Audemars Piguet · Royal Oak · Selfwinding · 15500ST",
    handle: "ap-royal-oak-selfwinding-15500st",
    vendor: "Audemars Piguet",
    tags: ["featured", "enquiry-only"],
    price: "0.00",
    metafields: {
      line: "royal-oak",
      reference_number: "15500ST.OO.1220ST.01",
      gender: "men",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 41,
      case_material: ["steel"],
      dial_color: "Blue",
      crystal: "Sapphire",
      water_resistance: "50m",
      strap_type: "bracelet",
      power_reserve: "60 hours",
      tier: "luxury",
      purchase_mode: "enquiry",
    },
  },
  {
    id: "5",
    title: "Patek Philippe · Nautilus · 5711/1A-010",
    handle: "patek-nautilus-5711-1a",
    vendor: "Patek Philippe",
    tags: ["limited", "enquiry-only"],
    price: "0.00",
    metafields: {
      line: "nautilus",
      reference_number: "5711/1A-010",
      gender: "men",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 40,
      case_material: ["steel"],
      dial_color: "Blue",
      crystal: "Sapphire",
      water_resistance: "120m",
      strap_type: "bracelet",
      power_reserve: "45 hours",
      tier: "luxury",
      purchase_mode: "enquiry",
    },
  },
  {
    id: "6",
    title: "Hublot · Classic Fusion · Titanium · 565.NX.1170.LR",
    handle: "hublot-classic-fusion-titanium",
    vendor: "Hublot",
    tags: ["bestseller"],
    price: "8900.00",
    metafields: {
      line: "classic-fusion",
      reference_number: "565.NX.1170.LR",
      gender: "men",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 42,
      case_material: ["titanium"],
      dial_color: "Black",
      crystal: "Sapphire",
      water_resistance: "50m",
      strap_type: "leather",
      power_reserve: "42 hours",
      tier: "luxury",
      purchase_mode: "checkout",
    },
  },
];
