import type { Brand, HomepageSlot, JournalArticle, WatchProduct } from "./types";

export const mockBrands: Brand[] = [
  {
    handle: "rolex",
    name: "Rolex",
    displayLines: ["Rolex"],
    tier: "haute",
    enquiry_only: true,
    tagline: "The crown of Swiss watchmaking",
    heritage:
      "Founded in 1905, Rolex has defined the modern luxury sports watch.",
    collection_handle: "rolex",
    logo: "/brands/rolex.png",
    collectionImage: "/collections/rolex.jpg",
    founded_year: 1905,
  },
  {
    handle: "audemars-piguet",
    name: "Audemars Piguet",
    displayLines: ["Audemars", "Piguet"],
    tier: "haute",
    enquiry_only: true,
    tagline: "To break the rules, you must first master them",
    heritage:
      "Since 1875, Audemars Piguet has pushed the boundaries of haute horlogerie.",
    collection_handle: "audemars-piguet",
    collectionImage: "/collections/audemars-piguet.jpg",
    founded_year: 1875,
  },
  {
    handle: "patek-philippe",
    name: "Patek Philippe",
    displayLines: ["Patek", "Philippe"],
    tier: "haute",
    enquiry_only: true,
    tagline: "You never actually own a Patek Philippe",
    heritage:
      "The last family-owned independent watch manufacturer in Geneva.",
    collection_handle: "patek-philippe",
    collectionImage: "/collections/patek-philippe.jpg",
    founded_year: 1839,
  },
  {
    handle: "hublot",
    name: "Hublot",
    displayLines: ["Hublot"],
    tier: "haute",
    enquiry_only: false,
    tagline: "The art of fusion",
    heritage:
      "Hublot pioneered the fusion of precious materials with innovative design.",
    collection_handle: "hublot",
    collectionImage: "/collections/hublot.jpg",
    founded_year: 1980,
  },
  {
    handle: "tissot",
    name: "Tissot",
    displayLines: ["Tissot"],
    tier: "premium",
    enquiry_only: false,
    tagline: "Innovators by tradition since 1853",
    heritage: "Tissot brings Swiss precision to accessible luxury.",
    collection_handle: "tissot",
    collectionImage: "/collections/tissot.jpg",
    founded_year: 1853,
  },
];

export const mockHomepageSlots: HomepageSlot[] = [
  {
    kind: "brand_chapter",
    heading: "Rolex",
    subheading: "The crown of Swiss watchmaking",
    image: "/collections/rolex.jpg",
    cta_label: "Explore Rolex",
    cta_href: "/collections/rolex",
    order: 1,
    founded_year: 1905,
    heritage:
      "Founded in 1905, Rolex has defined the modern luxury sports watch — from the Submariner to the Daytona, each reference is a chapter in precision.",
  },
];

export const mockJournalArticles: JournalArticle[] = [
  {
    title: "How to choose your first automatic watch",
    slug: "first-automatic-watch",
    hero: "/journal/first-automatic.jpg",
    excerpt: "Movement, case size, and everyday wear — a calm guide for first-time collectors.",
    author: "Editorial",
    published_at: "2026-08-12",
  },
  {
    title: "Why the PRX became a modern classic",
    slug: "tissot-prx-modern-classic",
    hero: "/journal/prx-classic.jpg",
    excerpt: "Integrated bracelet, Powermatic 80, and the return of 1970s sports elegance.",
    author: "Editorial",
    published_at: "2026-07-28",
  },
  {
    title: "Reading a reference number like a specialist",
    slug: "reading-reference-numbers",
    hero: "/journal/reference-numbers.jpg",
    excerpt: "What the digits reveal about line, material, dial, and bracelet.",
    author: "Concierge",
    published_at: "2026-06-04",
  },
];

export const mockProducts: WatchProduct[] = [
  {
    id: "1",
    title: "Tissot · PRX · Powermatic 80 · T137.407.11.041.00",
    handle: "tissot-prx-powermatic-80-blue",
    vendor: "Tissot",
    tags: ["new", "featured"],
    price: "195000",
    currencyCode: "PKR",
    imageUrl: "/collections/tissot.jpg",
    images: ["/collections/tissot.jpg", "/categories/automatic.jpg"],
    metafields: {
      line: "prx",
      reference_number: "T137.407.11.041.00",
      gender: "unisex",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 40,
      case_material: ["steel"],
      dial_color: "Blue",
      crystal: "Sapphire",
      water_resistance: "100m",
      strap_type: "bracelet",
      power_reserve: "80 hours",
      tier: "premium",
      purchase_mode: "checkout",
      is_limited: false,
      box_papers: "Full set",
      year_of_production: null,
      condition: "New",
      service_history: "",
    },
  },
  {
    id: "2",
    title: "Tissot · PRX · Powermatic 80 · T137.407.11.351.00",
    handle: "tissot-prx-powermatic-80-green",
    vendor: "Tissot",
    tags: ["new", "bestseller"],
    price: "195000",
    currencyCode: "PKR",
    imageUrl: "/categories/automatic.jpg",
    images: ["/categories/automatic.jpg", "/collections/tissot.jpg"],
    metafields: {
      line: "prx",
      reference_number: "T137.407.11.351.00",
      gender: "unisex",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 40,
      case_material: ["steel"],
      dial_color: "Green",
      crystal: "Sapphire",
      water_resistance: "100m",
      strap_type: "bracelet",
      power_reserve: "80 hours",
      tier: "premium",
      purchase_mode: "checkout",
      is_limited: false,
      box_papers: "Full set",
      year_of_production: null,
      condition: "New",
      service_history: "",
    },
  },
  {
    id: "3",
    title: "Rolex · Submariner · Date · 126610LN",
    handle: "rolex-submariner-date-126610ln",
    vendor: "Rolex",
    tags: ["featured", "enquiry-only"],
    price: "0.00",
    currencyCode: "PKR",
    imageUrl: "/collections/rolex.jpg",
    images: ["/collections/rolex.jpg", "/categories/luxury.jpg"],
    metafields: {
      line: "submariner",
      reference_number: "126610LN",
      gender: "men",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 41,
      case_material: ["steel"],
      dial_color: "Black",
      crystal: "Sapphire",
      water_resistance: "300m",
      strap_type: "bracelet",
      power_reserve: "70 hours",
      tier: "haute",
      purchase_mode: "enquiry",
      is_limited: false,
      box_papers: "Full set",
      year_of_production: null,
      condition: "Unworn",
      service_history: "",
    },
  },
  {
    id: "4",
    title: "Audemars Piguet · Royal Oak · Selfwinding · 15500ST",
    handle: "ap-royal-oak-selfwinding-15500st",
    vendor: "Audemars Piguet",
    tags: ["featured", "enquiry-only"],
    price: "0.00",
    currencyCode: "PKR",
    imageUrl: "/collections/audemars-piguet.jpg",
    images: ["/collections/audemars-piguet.jpg", "/categories/mens.jpg"],
    metafields: {
      line: "royal-oak",
      reference_number: "15500ST.OO.1220ST.01",
      gender: "men",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 41,
      case_material: ["steel"],
      dial_color: "Blue",
      crystal: "Sapphire",
      water_resistance: "50m",
      strap_type: "bracelet",
      power_reserve: "60 hours",
      tier: "haute",
      purchase_mode: "enquiry",
      is_limited: false,
      box_papers: "Full set",
      year_of_production: null,
      condition: "Unworn",
      service_history: "",
    },
  },
  {
    id: "5",
    title: "Patek Philippe · Nautilus · 5711/1A-010",
    handle: "patek-nautilus-5711-1a",
    vendor: "Patek Philippe",
    tags: ["limited", "enquiry-only"],
    price: "0.00",
    currencyCode: "PKR",
    imageUrl: "/collections/patek-philippe.jpg",
    images: ["/collections/patek-philippe.jpg", "/categories/premium.jpg"],
    metafields: {
      line: "nautilus",
      reference_number: "5711/1A-010",
      gender: "men",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 40,
      case_material: ["steel"],
      dial_color: "Blue",
      crystal: "Sapphire",
      water_resistance: "120m",
      strap_type: "bracelet",
      power_reserve: "45 hours",
      tier: "haute",
      purchase_mode: "enquiry",
      is_limited: true,
      box_papers: "Full set",
      year_of_production: null,
      condition: "Unworn",
      service_history: "",
    },
  },
  {
    id: "6",
    title: "Hublot · Classic Fusion · Titanium · 565.NX.1170.LR",
    handle: "hublot-classic-fusion-titanium",
    vendor: "Hublot",
    tags: ["bestseller"],
    price: "2490000",
    currencyCode: "PKR",
    imageUrl: "/collections/hublot.jpg",
    images: ["/collections/hublot.jpg", "/categories/chronograph.jpg"],
    metafields: {
      line: "classic-fusion",
      reference_number: "565.NX.1170.LR",
      gender: "men",
      movement: "automatic",
      is_chronograph: false,
      case_size_mm: 42,
      case_material: ["titanium"],
      dial_color: "Black",
      crystal: "Sapphire",
      water_resistance: "50m",
      strap_type: "leather",
      power_reserve: "42 hours",
      tier: "luxury",
      purchase_mode: "checkout",
      is_limited: false,
      box_papers: "Full set",
      year_of_production: null,
      condition: "New",
      service_history: "",
    },
  },
];
